---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: external-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.21.25-192.168.21.29
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: internal-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.21.30-192.168.21.40
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: l2-service-pool
  namespace: metallb
spec:
  addresses:
  - 192.168.21.41-192.168.21.50
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: ltwo
  namespace: metallb
spec:
  ipAddressPools:
  - l2-service-pool