---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 24h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale
  namespace: tailscale
spec:
  interval: 12h
  chart:
    spec:
      chart: tailscale-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
      interval: 12h
  timeout: 30s
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  values:
    oauth:
      clientId: ${tailscale_client_id}
      clientSecret: ${tailscale_client_secret}
---
apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  endpointSelector: {}
  ingress:
    # Health checks and probes
    - fromEntities:
        - host
        - remote-node
        - health
  egress:
    # DNS resolution
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    # Kubernetes API Server
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
    # Tailscale control plane and DERP relays
    - toEntities:
        - world

