apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: protect-namespaces
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: add-flux-prune-disabled
    match:
      resources:
        kinds:
        - Namespace
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            +(kustomize.toolkit.fluxcd.io/prune): disabled
