apiVersion: v1
kind: Secret
metadata:
  name: longhorn-backup-target-secret
  namespace: longhorn-system
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: ${longhorn_aws_access_key_id}
  AWS_SECRET_ACCESS_KEY: ${longhorn_aws_secret_access_key}
  AWS_REGION: ${longhorn_aws_region}
  S3_BUCKET: ${s3_bucket_longhorn}
