apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: ${longhorn_node_1}
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    ${longhorn_node_1}-nvme:
      allowScheduling: true
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
      storageReserved: 32212254720 # 30 Gb
      tags: []
  evictionRequested: false
  instanceManagerCPURequest: 0
  name: ${longhorn_node_1}
  tags: []
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: ${longhorn_node_2}
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    ${longhorn_node_2}-nvme:
      allowScheduling: true
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
      storageReserved: 32212254720
      tags: []
  evictionRequested: false
  instanceManagerCPURequest: 0
  name: ${longhorn_node_2}
  tags: []
---
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  name: ${longhorn_node_3}
  namespace: longhorn-system
spec:
  allowScheduling: true
  disks:
    ${longhorn_node_3}-nvme:
      allowScheduling: true
      diskType: filesystem
      evictionRequested: false
      path: /var/lib/longhorn/
      storageReserved: 2684354560000 # 2.5 Tb
      tags: []
  evictionRequested: false
  instanceManagerCPURequest: 0
  name: ${longhorn_node_3}
  tags: []
