apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-ntfy
  namespace: victoriametrics
data:
  config.yml: |
    http:
      addr: :8080
    ntfy:
      baseurl: https://ntfy.sh
      notification:
        topic: homelab-alerts-${domain}
        priority: |
          status == "firing" ? "urgent" : "default"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager-ntfy
  namespace: victoriametrics
  labels:
    app: alertmanager-ntfy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager-ntfy
  template:
    metadata:
      labels:
        app: alertmanager-ntfy
    spec:
      containers:
        - name: alertmanager-ntfy
          image: ghcr.io/alexbakker/alertmanager-ntfy:latest
          args:
            - --configs=/etc/alertmanager-ntfy/config.yml
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager-ntfy
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
      volumes:
        - name: config
          configMap:
            name: alertmanager-ntfy
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager-ntfy
  namespace: victoriametrics
  labels:
    app: alertmanager-ntfy
spec:
  selector:
    app: alertmanager-ntfy
  ports:
    - name: http
      port: 8080
      targetPort: 8080
