---
apiVersion: v1
kind: Namespace
metadata:
  name: homeassistant
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: gabe565
  namespace: homeassistant
spec:
  interval: 24h
  url: https://charts.gabe565.com
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant
spec:
  interval: 12h
  chart:
    spec:
      chart: home-assistant
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: gabe565
        namespace: homeassistant
      interval: 12h
  timeout: 30s
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 3m
  values:
    env:
      TZ: Europe/Stockholm
    ingress:
      main:
        enabled: true
        className: "traefik"
        hosts:
          - host: homeassistant.${domain}
            paths:
              - path: /
                pathType: Prefix
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        globalMounts:
          - path: /config
