apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - example.yaml
  - open-webui.yaml
  - ollama.yaml
  # - tailscale.yaml
  # - vaultwarden.yaml
  # - homeassistant.yaml
  # - homepage.yaml
  # - github-runners/
