apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # AI
  # - ai/ollama
  # - ai/open-webui

  # Demo / Testing
  - demo/example

  # Media
  # Getting
  # - media/getting/qbittorrent
  # - media/getting/prowlarr
  # - media/getting/jellyseerr
  - media/getting/dispatcharr

  # Sorting
  # - media/sorting/radarr
  # - media/sorting/sonarr
  # - media/sorting/bazarr

  # Playing
  - media/playing/jellyfin

  # Home Automation
  # - home-automation/homeassistant

  # Management
  - management/headlamp
  - management/homepage
  # - management/github-runners
  - management/ntfy

  # Security
  # - security/tailscale
  # - security/vaultwarden

  # Game Servers
  # - game-servers/skyrim-server
