apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # AI
  # - ai/ollama
  # - ai/open-webui

  # Demo / Testing
  - demo/example

  # Media
  # - media/arr
  - media/dispatcharr
  # - media/jellyfin

  # Home Automation
  # - home-automation/homeassistant

  # Management
  # - management/headlamp
  # - management/homepage
  # - management/github-runners

  # Security
  # - security/tailscale
  # - security/vaultwarden
