apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-traefik
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./components/networking/traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  retryInterval: 1m0s
  timeout: 5m0s
  wait: true
  dependsOn:
    - name: system-metallb-config
    - name: system-cert-manager-config
    - name: system-victoriametrics
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-substitutions