---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: jaeger
spec:
  interval: 24h
  url: https://jaegertracing.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: jaeger
spec:
  interval: 12h
  chart:
    spec:
      chart: jaeger
      version: "3.x"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: jaeger
      interval: 12h
  timeout: 5m
  install:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
    remediation:
      retries: 3
  upgrade:
    strategy:
      name: RetryOnFailure
      retryInterval: 2m
    remediation:
      retries: 3
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
      kafka: false
    storage:
      type: memory
    allInOne:
      enabled: true
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          cpu: 1000m
          memory: 1024Mi
      service:
        headless: false
        collector:
          otlp:
            grpc:
              name: otlp-grpc
              port: 4317
            http:
              name: otlp-http
              port: 4318
      ingress:
        enabled: true
        ingressClassName: traefik
        hosts:
          - jaeger.${domain}
    agent:
      enabled: false
    collector:
      enabled: false
    query:
      enabled: false
