---
apiVersion: v1
kind: Namespace
metadata:
  name: jaeger
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: jaegertracing
  namespace: jaeger
spec:
  interval: 24h
  url: https://jaegertracing.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jaeger
  namespace: jaeger
spec:
  interval: 12h
  chart:
    spec:
      chart: jaeger
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: jaegertracing
        namespace: jaeger
      interval: 12h
  timeout: 30s
  values:


    # Ingress configuration for Jaeger UI
    ingress:
      enabled: true
      # To enable:
      ingressClassName: traefik
      hosts:
        - jaeger.${domain}
