apiVersion: v1
kind: Namespace
metadata:
  name: oauth2-proxy
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 1h
  url: https://kostiantyn-matsebora.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: oauth2-proxy
  namespace: oauth2-proxy
spec:
  interval: 30m
  chart:
    spec:
      chart: simple-oauth2-proxy
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: oauth2-proxy
      interval: 12h
  # Timeout for Helm operations
  timeout: 10m
  values:
ingress:
    host: auth.${domain}
    auth:
      oidc:
        enabled: true
        issuerUrl: ${oauth2_issuer_url}
      config:
        clientId: ${oauth_client_id}
        clientSecret: ${oauth_client_secret}
        cookieSecret: ${oauth_client_cookie_secret}
        setAuthorizationHeader: true
        emailDomain: "*"
        cookieRefresh: 1m
        cookieExpire: 30m
        codeChallengeMethod: S256
        scope: "openid user groups"
      extraConfig: |
        cookie_name = ${oauth_client_cookie_name}
        whitelist_domains = "*.${domain}"
        set_xauthrequest = "true"
        reverse_proxy = "true"
        cookie_domains = ".${domain}"
        oidc_email_claim = "sub"