apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-cloudflare-config
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./components/networking/cloudflare/config
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  dependsOn:
    - name: system-cloudflare
    - name: secrets-kustomization
  retryInterval: 1m0s
  timeout: 5m0s
  wait: true
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-substitutions
