apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-pvc-annotations
spec:
  validationFailureAction: Audit
  background: true
  rules:
  - name: add-helm-resource-policy
    match:
      resources:
        kinds:
        - PersistentVolumeClaim
    mutate:
      patchStrategicMerge:
        metadata:
          annotations:
            +(helm.sh/resource-policy): keep
