apiVersion: v1
kind: Secret
metadata:
  name: simply-credentials
  namespace: cert-manager
type: Opaque
stringData:
  account-name: ${simply_account_name}
  api-key: ${simply_api_key}
  domain-filter: ${simply_domain}
