apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-kyverno
  namespace: flux-system
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./components/security/kyverno
  prune: true
  retryInterval: 1m0s
  timeout: 5m0s
  wait: false
  dependsOn:
    - name: system-victoriametrics
  postBuild:
    substituteFrom:
      - kind: Secret
        name: flux-substitutions