apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - gotk-sync.yaml

  # Secrets
  - secrets-repo.yaml

  # Components
  - flux-components.yaml

  # Services
  - flux-services.yaml
  # - ../cluster-oidc-admin.yaml
