apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: secrets-repo
  namespace: flux-system
spec:
  interval: 2m0s
  ref:
    branch: main
  secretRef:
    name: flux-system
  url: https://github.com/AntonBjornNilsson/cloud-gitops-secrets.git
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: secrets-kustomization
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./
  prune: true
  sourceRef:
    kind: GitRepository
    name: secrets-repo