apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-victoriametrics
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./components/victoriametrics
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: true
  # dependsOn:
  #   - name: system-traefik
