apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - host
        - remote-node
        - health
      toPorts:
        - ports:
            - port: "8080"
              protocol: TCP
  egress:
    # DNS Resolution
    - toEndpoints:
        - matchLabels:
            io.kubernetes.pod.namespace: kube-system
            k8s-app: kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
    # Kubernetes API Server
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
            - port: "6443"
              protocol: TCP
    # Outbound HTTPS for downloading vulnerability DBs (GitHub GHCR) and container image layers
    - toEntities:
        - world
      toPorts:
        - ports:
            - port: "443"
              protocol: TCP
