---
apiVersion: v1
kind: Namespace
metadata:
  name: trivy-system
  labels:
    app.kubernetes.io/part-of: trivy-operator
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: aqua
  namespace: trivy-system
spec:
  interval: 24h
  url: https://aquasecurity.github.io/helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: trivy-operator
  namespace: trivy-system
spec:
  interval: 12h
  chart:
    spec:
      chart: trivy-operator
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: aqua
        namespace: trivy-system
      interval: 12h
  install:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  upgrade:
    crds: CreateReplace
    strategy:
      name: RetryOnFailure
      retryInterval: 1m
  timeout: 5m
  values:
    operator:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 500m
          memory: 512Mi
    trivy:
      ignoreUnfixed: false
    serviceMonitor:
      enabled: false
